# Site settings
title: Murder Island
email: 
url: https://www.ahmalo.tk
description: "Murder Island is an awesome Roblox game made by Iliketomoveit007 and MrAhmalo."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Golegana

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SirAhmalo
  - title: Youtube
    url: https://www.youtube.com/channel/UC9_nacXHhL_kxE4tfL9jmVA

# Build settings
markdown: kramdown
permalink: pretty
